---
title: "Project Proposal"
output: html_document
---

**Description of the Data**
The NYC taxi dataset describes urban transportation trends, organized by year, month, and transportation type. 

Transportation Types Include:

- Yellow Taxis
- Green (Borough) Taxis
- Uber
- Lyft
- Via
- Juno

Important Variables for Exploration Include:

- VendorID (Type of Transportation)
- passenger_count (Amount of Passengers)
- trip_distance (Trip Distance)
- PULocationID (Pick-Up Location)
- DOLocationID (Drop-Off Location)
- fare_amount (Trip Cost)
- tip_amount (Tip Amount)
- tpep_pickup_datetime (Pick-Up Time)
- tpep_dropoff_datetime (Drop-Off Time) 

**Statistical Methods and Computational Steps**

One question that we plan to address is how fares change depending on factors including time of day, location, and type of transportation.

Additionally, we would like to analyze these trends across different years and periods, including holidays such as New Years Eve.

Furthermore, we plan to examine the differences between taxis and for-hire transportation including Uber and Lyft. 

To address differences in fares, we plan to create a linear regression model to predict fares depending on certain factors.

To analyze the differences in time periods, we plan to use a t-test to determine whether there is a difference in mean rates.

Finally, to examine the differences between transportation methods, we plan to use an ANOVA test to compare between more than two groups.

EXPAND ON COMPUTATIONAL STEPS HERE

**Code to Read the Data**

***.py file to read Parquet:***

```
import pandas as pd
import sys

def read_parquet(file_path):
  try:
    df = pd.read_parquet(file_path)
    print(f"Reading {file_path}...")
    print(df.head())
  except Exception as e:
    print(f"Error reading {file_path}: {e}")

if __name__ == "__main__":
    file_path = sys.argv[1]
    read_parquet(file_path)
```
***.sh file to process Parquet files:***
```
#!/bin/bash                                                                                                                                                                                          

BASE_DIR="./nyc-taxi-dataset"

for year in {2009..2023}; do
    YEAR_DIR="${BASE_DIR}/${year}"

    if [ -d "$YEAR_DIR" ]; then
        echo "Processing year: $year"

        for subfolder in $(ls "$YEAR_DIR"); do
            SUBFOLDER_PATH="${YEAR_DIR}/${subfolder}"

            if [ -d "$SUBFOLDER_PATH" ]; then
                for file in $(find "$SUBFOLDER_PATH" -name "*.parquet"); do
                    python3 read_parquet.py "$file"
                done
            fi
        done
    fi
done
```

**Link to GitHub Repository**
https://github.com/jbrottier/stat405project      
      
